version: "3.8"

volumes:
  db_data:
    driver: local

services:
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api
    volumes:
      - 'db_data:/bitnami/postgresql'

  prod:
    build:
      context: ./dockerfiles
      dockerfile: prod.Dockerfile
    container_name: api
    ports:
      - 3333:3333
    depends_on:
      - database
